### PR TITLE
Transition error handling fix

### LINKED ISSUE #288: Site stops responding when Winterwonderland is clicked twice
The site stops responding when you select the Winter Wonderland event twice from the menu.

Steps to reproduce:

1. Select the Winder Wonderland event from the menu
2. After you are at the event page, select that event again from the menu.

Result: Site stops responding.

Might be related to #289

### LINKED ISSUE #289: Clicking a hero/event page that you are already on, will lead instead to the Winter Wonderland
All links lead to the Winter Wonderland event.

Steps to reproduce:
1. Open the top menu or the side menu.
2. Click any hero/event EXCEPT Winter Wonderland.
3. Click the same hero/event.

Result: The page changes to Winter Wonderland.

### PR DESCRIPTION
**Pull request by Harmon758**
`INVALID_HERO` does not seem to be a valid error detail since https://github.com/Js41637/Overwatch-Item-Tracker/commit/c745557586f8f1e4ed0262ba8b659c76b1d0515a, so specifically handle `INVALID_EVENT` instead and default to transitioning to home state.
Also don't handle ignored transitions, so that clicking to transition to a page you're already on doesn't redirect to home page (would previously redirect to current event page; Fixes #289) or cause an infinite loop on the home page (previously on the current event page; Fixes #288).

### CODE REVIEW

File: js/app.js [hunk 1]
```diff
@@ -243,10 +243,10 @@ OWI.config(['$stateProvider', '$urlRouterProvider', function($stateProvider, $ur
 // Listen for state change errors such as routing to an invalid hero and redirect
 OWI.run(["$transitions", "$state", "DataService", function($transitions, $state, Data) {
   $transitions.onError({}, function(error) {
-    if (error.error().detail === 'INVALID_HERO') {
-      $state.go('home');
-    } else {
+    if (error.error().detail === 'INVALID_EVENT') {
       $state.go('events', { id: Data.currentEvent });
+    } else if (error.error().type !== RejectType.IGNORED) {
```
Comment (Js41637) [inline js/app.js]: `RejectType` doesn't exist. You should just get rid of the whole else if here and just make it an else.

Comment (Js41637) [reply js/app.js]: Oh right i forgot the reason for initially doing it, where does RejectType come from?

Comment (Harmon758) [reply js/app.js]: Yeah, I noticed this and I'm trying to figure out how to access the enum right now.
If there isn't a way, [`RejectType.IGNORED`](https://ui-router.github.io/ng1/docs/latest/enums/transition.rejecttype.html#ignored) can just be replaced by it's value, 5.
It's necessary to stop the infinite loop if the ignored transition is the same page, i.e. clicking the home button on the home page.

Comment (Js41637) [reply js/app.js]: Yeah I was just gonna say, just check for the error code 5 which seems to be the ignored code.

Comment (Harmon758) [reply js/app.js]: Ok, I'll commit that change right now if you want to merge, and maybe look into a better way later.

**Comment by Js41637** [comment]
Thanks for this.

**Comment by Harmon758** [comment]
I've been unable to find a way to reference [`RejectType.IGNORED`](https://ui-router.github.io/ng1/docs/latest/enums/transition.rejecttype.html#ignored), so it'd probably be best to just add a comment about it, e.g.  `    } else if (error.error().type !== 5) { // RejectType.IGNORED`.
I also noticed the comment above says `Listen for state change errors such as routing to an invalid hero and redirect` and that should be changed to "invalid event" now.
I don't think either of these changes warrant a PR, so I'll leave it to you, @Js41637.
